/**
 * Created by danding on 17/3/2.
 */


module.exports={
    'NOTIFICATION_RECV':'NOTIFICATION_RECV',
    'MAKE_MESSAGE_POP':'MAKE_MESSAGE_POP',
    'ON_MESSAGE_CLOSE':'ON_MESSAGE_CLOSE',
    'UPDATE_NOTIFICATIONS':'UPDATE_NOTIFICATIONS'
}
