/**
 * Created by dingyiming on 2017/2/28.
 */

module.exports={
    'SET_LIFE_HISTORY_ORDERS':'SET_LIFE_HISTORY_ORDERS',
    'SET_LIFE_PRICED_ORDERS':'SET_LIFE_PRICED_ORDERS',
    'SET_LIFE_APPLYED_ORDERS':'SET_LIFE_APPLYED_ORDERS',
    'ENABLE_LIFEORDERS_ONFRESH':'ENABLE_LIFEORDERS_ONFRESH',
    'DISABLE_LIFEORDERS_ONFRESH':'DISABLE_LIFEORDERS_ONFRESH',
    'SET_LIFE_PLANS':'SET_LIFE_PLANS',
    'SET_LIFE_PLAN_DETAIL':'SET_LIFE_PLAN_DETAIL'
}
