

module.exports={
    'SET_CAR_ORDERS_REFRESH':'SET_CAR_ORDERS_REFRESH',

    'SET_CAR_HISTORY_ORDERS':'SET_CAR_HISTORY_ORDERS',
    'SET_CAR_PRICED_ORDERS':'SET_CAR_PRICED_ORDERS',
    'SET_CAR_APPLYED_ORDERS':'SET_CAR_APPLYED_ORDERS',

    'ENABLE_CARORDERS_ONFRESH':'ENABLE_CARORDERS_ONFRESH',
    'DISABLE_CARORDERS_ONFRESH':'DISABLE_CARORDERS_ONFRESH',
}
