import _ from 'lodash';

module.exports={
    'SET_CAR_ORDERS_REFRESH':'SET_CAR_ORDERS_REFRESH',
    'UPDATE_CAR_HISTORY_ORDERS':'UPDATE_CAR_HISTORY_ORDERS',
    'UPDATE_APPLIED_CAR_ORDERS':'UPDATE_APPLIED_CAR_ORDERS',
    'DISABLE_CARORDERS_ONFRESH':'DISABLE_CARORDERS_ONFRESH'
}
