
module.exports={
    'PAGE_LOGIN':'PAGE_LOGIN',
    'PAGE_REGISTER':'PAGE_REGISTER',
    'PAGE_PASSWORDFORGET':'PAGE_PASSWORDFORGET',
    'UPDATE_PAGE_STATE':'UPDATE_PAGE_STATE',
    'UPDATE_NAVIGATOR':'UPDATE_NAVIGATOR'
}
