
module.exports={
    'UPDATE_SERVICE_ORDERS':'UPDATE_SERVICE_ORDERS',
    'UPDATE_MAP_CENTER':'UPDATE_MAP_CENTER',
    'SELECT_SERVICE_TAB':'SELECT_SERVICE_TAB',
    'ENABLE_SERVICE_ORDERS_REFRESH':'ENABLE_SERVICE_ORDERS_REFRESH',
    'DISABLE_SERVICE_ORDERS_REFRESH':'DISABLE_SERVICE_ORDERS_REFRESH',
    'ENABLE_SERVICE_ORDERS_CLEAR':'ENABLE_SERVICE_ORDERS_CLEAR'
}
