/**
 * Created by danding on 17/2/27.
 */
import _ from 'lodash';

module.exports={
    'AUTH_BY_OAUTH':'AUTH_BY_OAUTH',
    'ACCESS_TOKEN_ACK':'ACCESS_TOKEN_ACK',
    'UPDATE_PERSON_INFO':'UPDATE_PERSON_INFO',
    'UPDATE_SCORE':'UPDATE_SCORE',
    'SAVE_CONTACT_INFO':'SAVE_CONTACT_INFO',
    'UPDATE_CERTIFICATE':'UPDATE_CERTIFICATE'
}
