/**
 * Created by dingyiming on 2017/2/15.
 */
export const AUTH_BY_OAUTH = 'AUTH_BY_OAUTH';
export const ACCESS_TOKEN_ACK = 'ACCESS_TOKEN_ACK';
export const GET_PERSON_INFO='GET_PERSON_INFO';

//dashboard action
export const SELECT_CUSTOMER_CAR='SELECT_CUSTOMER_CAR';

//carOrders action
export const ENABLE_CARORDERS_ONFRESH='ENABLE_CARORDERS_ONFRESH';
export const DISABLE_CARORDERS_ONFRESH='DISABLE_CARORDERS_ONFRESH';
export const SET_CAR_HISTORY_ORDERS='SET_CAR_HISTORY_ORDERS';
export const SET_CAR_PRICED_AND_PRICING_ORDERS='SET_CAR_PRICED_AND_PRICING_ORDERS';
export const SET_CAR_APPLYED_ORDERS='SET_CAR_APPLYED_ORDERS';

//timer action
export const TIMER_SET='TIMER_SET';
export const TIMER_CLEAR='TIMER_CLEAR';
